/** Portable browser-only point/segment triangle-bound parity fixture runner. */
import { WebGPURenderer } from 'three/webgpu';
import { Fn, instancedArray, instanceIndex, uint, float, vec4, uniform, select } from 'three/tsl';
import {createPatch,updateFromCaptured,motionBuffers,disposePatch} from './HairSurface.js';
import {createSurfaceQuery} from './HairSurfaceQuery.js';
const f32=p=>p.map(Math.fround);
function setup(renderer,triangles,normals){const count=triangles.length,indices=Array.from({length:count*3},(_,i)=>i),patch=createPatch({bodyIndices:indices,sourceTriangleIds:Array.from({length:count},(_,i)=>i),sourcePositions:triangles.flat(2),sourceNormals:normals.flatMap(n=>[...n,...n,...n])}),surface=createSurfaceQuery(patch,motionBuffers(patch)),seed=uniform(0xffffffff,'uint'),alpha=uniform(1),input=instancedArray(2,'vec4'),output=instancedArray(15,'vec4');
 const build=(point,count,offset)=>Fn(()=>{const i=instanceIndex.add(offset),p=input.element(point?instanceIndex:uint(0)).xyz,q=input.element(uint(1)).xyz,hit=point?surface.query(p,seed,alpha):surface.querySegment(p,q,seed,alpha),base=i.mul(5);
 output.element(base).assign(vec4(hit.closest,hit.signedDistance));output.element(base.add(1)).assign(vec4(hit.segmentPoint??p,hit.segmentT??float(0)));output.element(base.add(2)).assign(vec4(hit.barycentric,select(hit.valid,float(1),float(0))));output.element(base.add(3)).assign(vec4(hit.normal,select(hit.openBoundary,float(1),float(0))));output.element(base.add(4)).assign(vec4(float(hit.sourceTriangle),float(hit.orderedTriangle),float(hit.nodesVisited),float(hit.trianglesTested)));})().compute(count).setName('triangle bound '+(point?'point':'segment')+' parity');
 const pointNode=build(true,2,0),segmentNode=build(false,1,2);
 return{patch,surface,seed,alpha,async run(c){const normal=c.normals.flatMap(n=>[...n,...n,...n]);updateFromCaptured(patch,(c.previousTriangles??c.triangles).flat(2),normal,{reset:true});updateFromCaptured(patch,c.triangles.flat(2),normal,{advanceHistory:true});surface.update();input.value.array.set([...f32(c.start),0,...f32(c.end),0]);input.value.needsUpdate=true;await renderer.computeAsync([pointNode,segmentNode]);const buffer=await renderer.getArrayBufferAsync(output.value);return {bits:Array.from(new Uint32Array(buffer)),values:Array.from(new Float32Array(buffer))};},dispose(){pointNode.dispose();segmentNode.dispose();surface.dispose(renderer);for(const b of [input,output])renderer._attributes?.delete(b.value);disposePatch(patch);}};
}
export async function runAdversarialBounds(fixtures){const renderer=new WebGPURenderer({canvas:document.createElement('canvas')});await renderer.init();if(!renderer.backend.isWebGPUBackend)throw Error('WebGPU required');const resource=()=>({storage:renderer.info.memory.storageAttributes,bytes:renderer.info.memory.storageAttributesSize,compute:[...renderer._pipelines.caches.values()].filter(x=>x.isComputePipeline).length});const before=resource(),states=new Map(),rows=[];
 try{for(const original of fixtures){const c={...original,triangles:original.triangles.map(t=>t.map(f32)),previousTriangles:original.previousTriangles?.map(t=>t.map(f32))},count=c.triangles.length;let state=states.get(count);if(!state){state=setup(renderer,c.triangles,c.normals);states.set(count,state);}
  for(const alpha of c.alphas??[1])for(const seed of [0xffffffff,0,count-1,0xfffffffe]){state.seed.value=seed;state.alpha.value=alpha;const result=await state.run(c);rows.push({name:c.name,alpha,seed,queryKinds:['start-point','end-point','whole-segment'],...result});}}
 }finally{for(const state of states.values())state.dispose();}
 const after=resource();renderer.dispose();return{before,after,rows};}
